prometheus:
  url: http://prometheus-server.monitoring.svc
  port: 80
rules:
  custom:
    - seriesQuery: 'http_requests_total{namespace!="",service!=""}'
      resources:
        overrides:
          namespace: {resource: "namespace"}
          service: {resource: "service"}
      name:
        matches: "http_requests_total"
        as: "http_requests_total"
      metricsQuery: >
        sum by (namespace, service) (rate(http_requests_total{<<.LabelMatchers>>,endpoint="/api/check_vehicle/"}[2m]))