apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: vehicle-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: srpillai/vehicleapp-backend-bloom:latest
          imagePullPolicy: Always
          env:
            - name: MONGO_HOST
              value: db
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB
              value: vehicle_db
            - name: MONGO_USER
              value: admin
            - name: MONGO_PASSWORD
              value: admin
          ports:
            - containerPort: 80