apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: vehicle-app
spec:
  selector:
    app: db
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: vehicle-app
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081