# Backend service for the frontend to connect to
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: vehicle-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "80"
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP