apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
    version: green
  name: frontend-green
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
    version: green
  type: LoadBalancer
status:
  loadBalancer: {}