apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
  labels:
    app: frontend
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      version: green
  template:
    metadata:
      labels:
        app: frontend
        version: green
    spec:
      containers:
        - name: frontend
          image: 874954573048.dkr.ecr.us-east-1.amazonaws.com/vehicle-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
