apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 874954573048.dkr.ecr.us-east-1.amazonaws.com/vehicle-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80