apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
    version: dynamic_version
  name: frontend-prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
    version: dynamic_version
  type: LoadBalancer
status:
  loadBalancer: {}