variable "project_name" {}
variable "cluster_version" {}
variable "vpc_id" {}
variable "vpc_private_subnets" {}
variable "node_group_ami_type" {}
variable "node_group_name" {}
variable "node_group_instance_type" {}
variable "node_group_min_size" {}
variable "node_group_max_size" {}
variable "node_group_desired_size" {}
